#!/bin/bash

DIRNAME=`dirname "$0"`
if [ "$DIRNAME" = "." ]; then
  DIRNAME="$PWD"
fi

export PID=$$

if [ "$JAVA" = "" ]; then
  JAVA=`which java`
  if [ "$JAVA" = "" ]; then
    if [ "$JAVA_HOME" = "" ]; then
      echo 'Unable to start a JVM : $JAVA is not set and java is not in PATH and $JAVA_HOME is not set'
      exit
    fi
    JAVA="$JAVA_HOME/bin/java"
  fi
fi


DECLARE_PDF_TOOLS_OPTS=$(echo "$DECLARE_PDF_TOOLS_OPTS" | grep "^\(declare\|typeset\) -ax\? PDF_TOOLS_OPTS=")
if [ "${#DECLARE_PDF_TOOLS_OPTS}" -ne 0 ]; then
  eval "$DECLARE_PDF_TOOLS_OPTS" >/dev/null 2>&1 || PDF_TOOLS_OPTS=($JAVA_OPTS)
else
  PDF_TOOLS_OPTS=($JAVA_OPTS)
fi

PDF_TOOLS_OPTS=(${PDF_TOOLS_OPTS[@]} -Dlogback.logDirectory="$DIRNAME/log")
PDF_TOOLS_OPTS=(${PDF_TOOLS_OPTS[@]} -Dlogback.configurationFile="$DIRNAME/logback.xml")

DECLARE_PDF_TOOLS_ARGS=$(echo "$DECLARE_PDF_TOOLS_ARGS" | grep "^\(declare\|typeset\) -ax\? PDF_TOOLS_ARGS=")
if [ "${#DECLARE_PDF_TOOLS_ARGS}" -ne 0 ]; then
  eval "$DECLARE_PDF_TOOLS_ARGS" >/dev/null 2>&1 || PDF_TOOLS_ARGS=()
else
  PDF_TOOLS_ARGS=()
fi

exec "$JAVA" "${PDF_TOOLS_OPTS[@]}" -jar "$DIRNAME/lib/pdf_tools.cli-${project.version}.jar" "${PDF_TOOLS_ARGS[@]}" "$@"
